###  Correct request
GET https://v95tcmrgmd.execute-api.eu-north-1.amazonaws.com/Prod/divide?dividend=2&divisor=3
Accept: application/json
api-key: someCoolSecret

###  Missing Parameters
GET https://v95tcmrgmd.execute-api.eu-north-1.amazonaws.com/Prod/divide
Accept: application/json
api-key: someCoolSecret




