###  Correct request
GET https://w14fyo8jpj.execute-api.eu-north-1.amazonaws.com/Prod/divide?dividend=6&divisor=2
Accept: application/json
api-key: someCoolSecret

###  Missing Parameters
GET https://w14fyo8jpj.execute-api.eu-north-1.amazonaws.com/Prod/divide
Accept: application/json
api-key: someCoolSecret

###  ArithmeticException
GET https://w14fyo8jpj.execute-api.eu-north-1.amazonaws.com/Prod/divide?dividend=6&divisor=0
Accept: application/json

###  NumberFormatException
GET https://w14fyo8jpj.execute-api.eu-north-1.amazonaws.com/Prod/divide?dividend=NaN&divisor=2
Accept: application/json




