### Create new comment
POST  https://ubqqu9m585.execute-api.eu-north-1.amazonaws.com/Prod/comments
Content-Type: application/json
Accept: application/json

{
  "pageId":   "one-cool-news",
  "userName": "The great author {{$randomInt}}",
  "message":  "I really enjoyed this story! {{$uuid}}"
}

###
GET  https://ubqqu9m585.execute-api.eu-north-1.amazonaws.com/Prod/comments/one-cool-news
Accept: application/json

###
