POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Nazar",
  "lastName": "Shyshkin"
}

###

POST https://89sldcq35g.execute-api.eu-north-1.amazonaws.com/Prod/users/
Content-Type: application/json

{
  "firstName": "Nazar",
  "lastName": "Shyshkin"
}

