POST https://w9ftu2qts5.execute-api.eu-north-1.amazonaws.com/Prod/users
Content-Type: application/json

{
  "email":"kateshyshkina@mailinator.com",
  "password":"12345678",
  "firstName":"Kate",
  "lastName":"Shyshkina"
}

###
