POST https://w9ftu2qts5.execute-api.eu-north-1.amazonaws.com/Prod/login
Content-Type: application/json

{
  "email":"kateshyshkina@mailinator.com",
  "password":"12345678"
}

### Login Wrong PASSWORD
POST https://w9ftu2qts5.execute-api.eu-north-1.amazonaws.com/Prod/login
Content-Type: application/json

{
  "email":"kateshyshkina@mailinator.com",
  "password":"wrong"
}

### Login PASSWORD is null
POST https://w9ftu2qts5.execute-api.eu-north-1.amazonaws.com/Prod/login
Content-Type: application/json

{
  "email":"kateshyshkina@mailinator.com"
}
