AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  data-transformation-example

  Sample SAM Template for data-transformation-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  PostHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DataTransformationExample
      Handler: net.shyshkin.study.aws.serverless.transformation.photoapp.users.PostHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        PhotoAppUsers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DataTransformationExampleApi
            Path: /users
            Method: post

  DataTransformationExampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: Data Transformation API
      Description: Data Transformation Example REST API (API Gateway)
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: data-transformation-example-Prod-oas30-apigateway.yaml
#      Models:
#        CreateUserLambdaInput:
#          type: object
#          title: Create User Lambda Input Model Schema
#          required:
#            - firstName
#            - lastName
#            - email
#            - password
#            - repeatPassword
#          properties:
#            firstName:
#              type: string
#              description: User's First Name
#            lastName:
#              type: string
#              description: "User's Last Name"
#            email:
#              type: string
#              description: "User's Email"
#            password:
#              type: string
#              description: "User's Password"
#            repeatPassword:
#              type: string
#              description: "User's Password Repeat"
#            age:
#              type: integer
#              description: "User's age"
#
#        CreateUserLambdaOutput:
#          type: object
#          title: Create User Output Lambda Model Schema
#          properties:
#            firstName:
#              type: string
#            lastName:
#              type: string
#            email:
#              type: string
#            id:
#              type: string
#              description: Unique user identifier

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DataTransformationExampleApi:
    Description: "API Gateway endpoint URL for Prod stage for DataTransformationExample function"
    Value: !Sub "https://${DataTransformationExampleApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users"
  PostHandlerFunction:
    Description: "PostHandlerFunction ARN"
    Value: !GetAtt PostHandlerFunction.Arn
  PostHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for PostHandlerFunction"
    Value: !GetAtt PostHandlerFunctionRole.Arn
