openapi: "3.0.1"
info:
  title: "My Division REST API"
  description: "API to study Error Handling in Serverless Apps"
  version: "1.0"
servers:
- url: "https://1wt9plz7ig.execute-api.eu-north-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/Prod"
paths:
  /divide:
    get:
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DivisionExampleFunction.Arn}/invocations' #DivisionExampleFunction.Arn
        passthroughBehavior: "when_no_match"
    post:
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "POST"
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DivisionExampleNonProxyFunction.Arn}/invocations' #DivisionExampleNonProxyFunction.Arn
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
components: {}
