AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  error-response-example

  Sample SAM Template for error-response-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  DivisionExampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ErrorResponseExample
      Handler: net.shyshkin.study.aws.serverless.error.DivisionExampleFunction::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        DivisionExample:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DivisionRestApi
            Path: /divide
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute

  DivisionExampleNonProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ErrorResponseExample
      Handler: net.shyshkin.study.aws.serverless.error.DivisionExampleNonProxyFunction::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        DefaultErrorResponseExample:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DivisionRestApi
            Path: /divide
            Method: post

  DivisionRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: My Division REST API
      Description: API to study Error Handling in Serverless Apps
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: My Division REST API-Prod-oas30-apigateway.yaml

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DivisionExampleApi:
    Description: "API Gateway endpoint URL for Prod stage for Division Example function"
    Value: !Sub "https://${DivisionRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/divide?dividend=6&divisor=2"
  DivisionExampleNonProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Division Example Non Proxy function (POST)"
    Value: !Sub "https://${DivisionRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/divide"
  DivisionExampleFunction:
    Description: "Division Example Lambda Function ARN"
    Value: !GetAtt DivisionExampleFunction.Arn
  DivisionExampleFunctionIamRole:
    Description: "Implicit IAM Role created for Division Example function"
    Value: !GetAtt DivisionExampleFunctionRole.Arn
