AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  environment-variables-example

  Sample SAM Template for environment-variables-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Environment:
      Variables:
        MY_GLOBAL_VARIABLE: AQICAHhJFGAnVhYAPnsHwblpOqU1qgM5vu37AIZk+pkNU6kxSgEnjSIDSo3/HcorlAcO50xcAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6w6+3HU74uwwhuAxAgEQgCsAPFzqNLi+nyv9ba/jX0J4sBbXmLY94hMQ7X5heN9kfdGQyb+ie1/zu94z
Resources:
  EnvironmentVariablesExampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: EnvironmentVariablesExample
      Handler: net.shyshkin.study.aws.serverless.environment.EnvironmentVariablesExample::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          MY_VARIABLE: AQICAHhJFGAnVhYAPnsHwblpOqU1qgM5vu37AIZk+pkNU6kxSgH0FFKwiu2sa+tprVHFlREIAAAAdDByBgkqhkiG9w0BBwagZTBjAgEAMF4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDnhBroWvjgaqVbH1AgEQgDE64Sp12MzWQFZsrN6px7M9ls6aOXkSobLDBWlXDa8Hm5BA9efmYC/Ct1jEMDcUAhkL
          MY_COGNITO_USER_POOL_ID: AQICAHhJFGAnVhYAPnsHwblpOqU1qgM5vu37AIZk+pkNU6kxSgGoM6ELfTu++UCpEYiPwprmAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzMbTZJ/gsUEdTlzYAgEQgCJJp4zJK9jRTZWYC+LK7iyhhPFap3C0PqOq10zoRNTG8KD4
          MY_COGNITO_CLIENT_APP_SECRET: AQICAHhJFGAnVhYAPnsHwblpOqU1qgM5vu37AIZk+pkNU6kxSgF5wsDM4B4wY6p5S9eVk9nQAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwwWNrT6pWTnHeVQUAgEQgCSxB77UkCzxbhJJzbyY+W0j96cPO71e/gT5qpsuSk7HKNumblc=
      Events:
        EnvironmentVariablesExample:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EnvironmentVariablesExampleApi:
    Description: "API Gateway endpoint URL for Prod stage for Environment Variables Example function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EnvironmentVariablesExampleFunction:
    Description: "Environment Variables Example Lambda Function ARN"
    Value: !GetAtt EnvironmentVariablesExampleFunction.Arn
  EnvironmentVariablesExampleFunctionIamRole:
    Description: "Implicit IAM Role created for Environment Variables Example function"
    Value: !GetAtt EnvironmentVariablesExampleFunctionRole.Arn
