---
swagger: "2.0"
info:
  version: "2021-11-29T09:06:11Z"
  title: "Users Mock API"
host: "bfvrrtg4l2.execute-api.eu-north-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /users:
    get:
      description: "Returns a list of all users."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "count"
        in: "query"
        description: "The 'count' Query String Parameter is used to limit the number\
          \ of users to return."
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /users/{userId}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "The id of user to return. The value of userId is UUID."
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
