POST  {{serverUrl}}/users
Content-Type: application/json

{
  "userFirstName": "Arina",
  "userLastName": "Shyshkina",
  "userEmail": "d.art.shishkin@gmail.com",
  "userPassword": "123",
  "userRepeatPassword": "321",
  "userAge": 11
}

###

POST  {{serverUrl}}/users?userSecretKey=123param
Content-Type: application/json

{
  "userFirstName": "Arina",
  "userLastName": "Shyshkina",
  "userEmail": "d.art.shishkin@gmail.com",
  "userPassword": "123",
  "userRepeatPassword": "321",
  "userAge": 11
}

###

POST  {{serverUrl}}/users
Content-Type: application/json
userSecretKey: 321headers

{
  "userFirstName": "Arina",
  "userLastName": "Shyshkina",
  "userEmail": "d.art.shishkin@gmail.com",
  "userPassword": "123",
  "userRepeatPassword": "321",
  "userAge": 11
}
