version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PhotoAppUsersRestApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1alt62pqr870u"
s3_prefix = "PhotoAppUsersRestApi"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
